### PR TITLE
Add test pins

### PR DESCRIPTION
**Pull request by bcostm**

### CODE REVIEW

**Comment by 0xc0170** [comment]
+1

**Comment by 0xc0170** [comment]
Please merge and release the new version

**Comment by bcostm** [comment]
ok it's merged.
Now, for the new release are these steps ok ?
- change the version in target.json file + send a pull request again + merge
- and then ? "yotta version patch command" ?

**Comment by 0xc0170** [comment]
Pull rebase your repository with this merge there, do (in this case use patch version as it's not breaking):

```
# create a new version patch
yotta version patch
# check if the new version is created (new commit, everythign is OK for the release !)
# publishing the repo, first publish to see you can publish this, then you can do git push
yotta publish
# this pushed the version commit and a new tag to origin
# origin should be this repo, you can verify that git remote -v (to check if it's really origin - github.com/ARMmbed/target-st-nucleo-f401re-gcc)
git push origin master --tags
```

**Comment by bcostm** [comment]
What I am not sure is the version written in the target.json file: do I need to change it myself or "yotta version" will do it automagically ?

**Comment by 0xc0170** [comment]
yotta does it, try it locally to see what does

**Comment by bcostm** [comment]
The "yotta version patch" command has well increased the version in the target.json file. But
when I've launched "yotta publish", I've got this error:
```
info: generate archive extracting to "st-nucleo-f401re-gcc-0.2.1"
error: server returned status 403: {"error":"not module owner"}
error: request exception occurred
```
Is it normal ? I thought I had the write access ?

**Comment by 0xc0170** [comment]
@bcostm I just added you to the owners, wolfgand was there only

**Pull request merged**
